---
title: "Tableau"
format: html
---

In this module, you will learn all about Tableau, a powerful business intelligence application that allows users to quickly create in-depth visualizations. This class will be light on programming to give you plenty of time to gain hands-on experience working with Tableau. During each class, you’ll complete a series of exercises to expand your knowledge. To begin, you’ll learn the basics of working in Tableau: importing, loading, joining, and splitting data. Later in the week, you’ll practice more advanced skills, including how to create groups, sets, and custom calculations. The lessons will build in complexity, culminating in a mini-project where you will work in pairs or groups of three to explore data and create visualizations in Tableau using at least two of your own data sources.

## Introduction to Tableau

#### Overview

In today’s lesson, you’ll be introduced to Tableau and many of its built-in functions. To begin, your instructor will give a brief introduction to Tableau and confirm that everyone has correctly installed Tableau Public. Then, you’ll complete a series of hands-on activities on how to load and explore data, create visualizations, and join and split data in Tableau. After a short break, you will complete two more activities in Tableau: In the first, you will create charts to compare candies to practice your sizing, coloring, and labeling skills. In the final activity, you will practice your storytelling skills by developing a visualization to illustrate the best-paid college major and the impact of attending graduate school on long-term pay.

#### What You'll Learn

- By the end of this lesson, you will be able to do the following using Tableau:

- Import data from various sources, including CSV files and Excel spreadsheets.

- Perform joins on multiple data sources.

- Create and customize basic visualizations.

- Create storyboards.

## Deeper into Tableau

#### Overview

In today’s lesson, you’ll expand your Tableau knowledge to gain experience in more advanced tasks, including custom calculations, maps, and level-of-detail calculations. To get started, your instructor will begin with an overview of how to create groups and sets in Tableau. Then, you’ll practice these new skills in an activity using movie rental data. Next, you will practice calculations by creating visualizations using a dataset on motor vehicle accidents in New York City. After a short break, you will complete three more activities in the second half of class: One on mapping, a second on creating a dashboard, and in the third and final activity of the class, you’ll practice creating level of detail (LOD) calculations with sample data.

#### What You'll Learn

- By the end of this lesson, you will be able to do the following using Tableau:

- Create groups and sets.

- Create maps and use built-in U.S. Census data.

- Create custom calculations.

- Apply LOD calculations.

- Create dashboards.

