project:
  type: book
  output-dir: ../docs

book:
  title: "Data Analysis Notes"
  author: "Angel Alcala Ruiz"
  date: "10/19/2023"
  chapters:
    - index.qmd
    - part: "PART 1. ABOUT DATA"
      chapters: 
        - data-tables.qmd
    - part: "PART 2. DATA VISUALIZATIONS"
      chapters: 
        - visualization-basics.qmd
    - part: "PART 3. PROGRAMMING IN R"
      chapters: 
        - intro-to-r.qmd
        - r-api.qmd
    - part: "PART 4. PROGRAMMING IN PYTHON"
      chapters:
        - intro-to-python.qmd
        - python-api.qmd
    - part: "PART 5. SQL"
      chapters:
        - sql.qmd
        - advanced-sql.qmd
        - data-collection.qmd
        - nosql-databases.qmd
        - etl.qmd
    - part: "PART 6. INTERACTIVE VISUALIZATIONS"
      chapters:
        - interactive-visualizations.qmd
        - advanced-interactive-visualizations.qmd
        - tableau.qmd
    - part: "PART 7. MACHINE LEARNING"
      chapters:
        - unsupervised-learning.qmd
        - supervised-learning.qmd
        - neural-networks-and-deep-learning.qmd
    - part: "PART 8. BIG DATA"
      chapters:
        - big-data.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: simplex
    code-fold: show
    code-tools: true
    number-depth: 3
    toc-depth: 3 


  pdf:
    documentclass: scrreprt


