project:
  type: book
  output-dir: ../docs

book:
  title: "Data Analysis Handbook"
  subtitle: "How to Collect, Clean, Analyze, & Visualize Data"
  author: "Angel Alcala Ruiz"
  date: "10/19/2023"
  navbar: 
    search: true
    right:
      - icon: globe2
        href: https://alcalar.com
        text: Personal Website
        target: _blank
      - icon: github
        href: https://github.com/dejesusalcala
        text: github
        target: _blank
  chapters:
    - index.qmd
    - part: "PART 1. ABOUT DATA"
      chapters: 
        - what-is-data-analysis.qmd
        - how-to-think-about-data.qmd
        - data-storage.qmd
        - how-programs-handle-data.qmd
    - part: "PART 2. PROGRAMMING IN R"
      chapters: 
        - intro-to-r.qmd
        - r-api.qmd
    - part: "PART 3. PROGRAMMING IN PYTHON"
      chapters:
        - intro-to-python.qmd
        - python-api.qmd
    - part: "PART 4. SQL"
      chapters: 
        - sql.qmd
        - advanced-sql.qmd
        - data-collection.qmd
        - nosql-databases.qmd
        - etl.qmd
    - part: "PART 5. DATA VISUALIZATIONS"
      chapters: 
        - visualization-basics.qmd
        - colors.qmd
        - interactive-visualizations.qmd
        - advanced-interactive-visualizations.qmd
        - tableau.qmd
    - part: "PART 6. MACHINE LEARNING"
      chapters:
        - unsupervised-learning.qmd
        - supervised-learning.qmd
        - neural-networks-and-deep-learning.qmd
    - part: "PART 8. BIG DATA"
      chapters:
        - big-data.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      light: [../css/theme-light.scss]
      dark: [../css/theme-dark.scss]
    code-fold: show
    code-tools: true
    number-depth: 3
    toc-depth: 3 


  pdf:
    documentclass: scrreprt


